version: "3.7"
services:
    db:
        image: postgres:12.2-alpine
        restart: always
        environment:
            POSTGRES_USER: wazuplay
            POSTGRES_PASSWORD: ${DBPASSWORD}
    oauth-server:
        build:
            context: ../.
            dockerfile: ./build/package/oauth-server/Dockerfile
