version: "3.7"
services:
    dev:
        build:
            context: ./.devcontainer/
            dockerfile: ./Dockerfile
        tty: true
        volumes:
            - .:/workspace:cached
    pgweb:
        image: sosedoff/pgweb
        ports:
            - "8081:8081"