version: "3.7"
services:
    dev-go:
        build:
            context: ./.devcontainer/
            dockerfile: ./Dockerfile-go
        tty: true
        volumes:
            - .:/workspace:cached
        ports:
            - "8080:8080"
    dev-node:
        build:
            context: ./.devcontainer/
            dockerfile: ./Dockerfile-node
        tty: true
        volumes:
            - ./web/player-frontend:/workspace:cached
        ports:
            - "3000:3000"
    pgweb:
        image: sosedoff/pgweb
        ports:
            - "8081:8081"