version: "3.7"
services:
    db:
        image: postgres:12.2-alpine
        restart: always
        environment:
            POSTGRES_USER: wazuplay
            POSTGRES_PASSWORD: test
        volumes:
            - ./init/initdb/:/docker-entrypoint-initdb.d/
    dev:
        build:
            context: ./.devcontainer/
            dockerfile: ./Dockerfile
        tty: true
        volumes:
            - .:/workspace:cached
    pgweb:
        image: sosedoff/pgweb
        ports:
            - "8081:8081"