version: "3.7"
services:
    dev:
        build:
            context: ./.devcontainer
            dockerfile: ./Dockerfile
        tty: true
        volumes:
            - .:/workspace:cached
            - ${SAVE_FOLDER}/.dev:/wazuplay-files
        ports:
            - "8080:8080"
    pgweb:
        image: sosedoff/pgweb
        ports:
            - "8081:8081"