version: "3.7"
services:
    nginx-proxy:
        build:
            context: ./
            dockerfile: ./build/package/nginx-proxy/Dockerfile
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
    db:
        image: postgres:12.2-alpine
        restart: always
        environment:
            POSTGRES_USER: wazuplay
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./init/initdb/:/docker-entrypoint-initdb.d
            - ${SAVE_FOLDER}/postgres:/var/lib/postgresql/data
    mail:
        image: catatnight/postfix
        environment: 
            maildomain: ${HOSTNAME}
            smtp_user: wazuplay:${SMTP_PASSWORD}
    oauth-server:
        build:
            context: ./
            dockerfile: ./build/package/oauth-server/Dockerfile
        environment: 
            VIRTUAL_HOST: oauth.${DOMAIN}
    image-server:
        build:
            context: ./
            dockerfile: ./build/package/image-server/Dockerfile
        environment: 
            VIRTUAL_HOST: images.${DOMAIN}
        volumes:
            - ${SAVE_FOLDER}/images:/wazuplay-files/images
    audio-server:
        build:
            context: ./
            dockerfile: ./build/package/audio-server/Dockerfile
        environment: 
            VIRTUAL_HOST: audio.${DOMAIN}
        volumes:
            - ${SAVE_FOLDER}/audio:/wazuplay-files/audio