name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: generate .env
      run: echo -e "HOSTNAME=localhost\nDBPASSWORD=test\nSMTP_PASSWORD=test" > .env
    - name: Build the Docker image
      run: docker-compose -f ./docker-compose.yml build